# テーマの選択
theme: jekyll-theme-minimal

# 絵文字表示のためのプラグイン
plugins:
  - jemoji

# ビルドの対象から除外するファイル
exclude:
  - README.md

# ///// 以下はリポジトリの都合上書いているだけなので、コピペ不要な箇所です /////
adc_url: 'https://adventar.org/calendars/3865'
adc_article_url: '#'
