# テーマの選択
theme: jekyll-theme-minimal

# 絵文字表示のためのプラグイン
plugins:
  - jemoji

# ビルドの対象から除外するファイル
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - .bundle
  - .gitignore
  - .sass-cache
  - sample_002.md # Sample 1 のビルド時にコメントアウトを外す

# リポジトリに関する情報を書く (Sample 2 のビルドに必要)
username: tsutaj # 自分の GitHub ユーザー名
repo: pages-example # リポジトリ名
destination: _site/

# /// 以下はリポジトリの都合上書いている (Getting Started では説明しません) ///
adc_url: 'https://adventar.org/calendars/3865'
adc_article_url: '#'

# baseurl は、基本的にリポジトリ名と一致させる
# リポジトリ名が [username].github.io の場合は baseurl = '/' とする
baseurl: '/pages-example/'
show_downloads: true

# 適宜、自分の情報に書き換えましょう
title: 'pages-example'
description: 'Competitive Programming Advent Calendar 2019 用のリポジトリ'

github:
  is_project_page: true
  repository_url: 'https://github.com/tsutaj/pages-example/'
  repository_nwo: 'tsutaj/pages-example'
  zip_url: 'https://github.com/tsutaj/pages-example/archive/master.zip'
  tar_url: 'https://github.com/tsutaj/pages-example/archive/master.tar.gz'
  owner_url: 'https://github.com/tsutaj/'
  owner_name: 'tsutaj'
